SELECT * FROM marcas;

SELECT * FROM categorias;

SELECT * FROM productos;

SELECT NOMBRE, MODELO,DESCRIPCION,PRECIO,PUNTUACION 
	FROM productos;
	
SELECT NOMBRE,(PRECIO/PUNTUACION)
	FROM productos;

SELECT * FROM productos
	WHERE PRECIO < 1000;

SELECT * FROM productos
	WHERE NOMBRE = "Wii";

SELECT NOMBRE,PRECIO FROM productos
	WHERE PRECIO < 1000 AND PRECIO > 1000;

SELECT NOMBRE,PRECIO FROM productos
	WHERE PRECIO < 1000 OR PRECIO > 1000;

SELECT NOMBRE, PRECIO,PUNTUACION FROM productos
	WHERE PRECIO >= 1000 AND PRECIO <= 10000 OR PUNTUACION > 4;

SELECT NOMBRE FROM clientes 
	ORDER BY NOMBRE ASC;

SELECT NOMBRE,APELLIDO FROM clientes
	ORDER BY NOMBRE, APELLIDO ASC;

SELECT NOMBRE,APELLIDO,TELEFONO,FECHA_DE_NACIMIENTO FROM clientes
	WHERE TELEFONO IS NOT NULL
	ORDER BY FECHA_DE_NACIMIENTO DESC;

SELECT NOMBRE,PUNTUACION FROM productos
	ORDER BY PUNTUACION DESC LIMIT 5;

SELECT NOMBRE,PUNTUACION FROM productos
	ORDER BY PUNTUACION DESC LIMIT 10,5;

SELECT NOMBRE FROM productos
	WHERE NOMBRE LIKE "IPHONE%";

SELECT NOMBRE FROM productos
	WHERE NOMBRE LIKE "%P%";

SELECT NOMBRE FROM productos
	WHERE NOMBRE LIKE "%P%P%";

SELECT "HOLA MUNDO" FROM clientes;

SELECT CONCAT_WS(', ', nombre, apellido) AS NOMBRE_COMPLETO FROM clientes;