SELECT CURDATE();

SELECT NOW();

SELECT FLOOR (DATEDIFF(curdate(),'1999-07-05')/365) AS 'TENES AÑOS VIVIDOS';

SELECT DATEDIFF(CURDATE(),"1999-07-05") AS "DIAS VIVIDOS"

SELECT DATE_FORMAT('2000-05-10',"%Y/%m/%d")

SELECT DATE_ADD(CURDATE(),INTERVAL 10 YEAR)

SELECT DATE_SUB(CURDATE(), INTERVAL 5 MONTH)

SELECT TRIM("   HOLA COMO ESTAS   ")

SELECT REPLACE("40-8595678-9","-","")

SELECT LEFT("40-8595678-9",2)

SELECT LENGTH("MURCIELAGO")

SELECT UPPER("Hoy Estoy Aprendiendo Funciones De Fecha")

SELECT LOWER("Hoy Estoy Aprendiendo Funciones De Fecha")

SELECT CONCAT('Realizo',SPACE(1),'El',SPACE(1), 'Curso',SPACE(1), 'Curso',SPACE(1),'De',SPACE(1),'Base',SPACE(1),'Datos');